{% set name = "geogif" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geogif-{{ version }}.tar.gz
  sha256: 91c08b3a2cfa73ac7be5d8523d645e9d05d7a2a131667f771758fa3feee3f4f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - dask-core >=2021.4.1
    - numpy >=1.20.2,<2.0.0
    - pillow >=10.1.0,<11.0.0
    - matplotlib-base >=3.4.1,<4.0.0
    - xarray >=0.18
    - typing_extensions

test:
  imports:
    - geogif
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://geogif.readthedocs.io/en/latest/index.html
  summary: Render xarray timestacks into GIFs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
