{% set name = "geogif" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geogif-{{ version }}.tar.gz
  sha256: 204b18a631c3a6cd05b74422fdc7725ceb819871fe8e4f36c065c8947c0b4d3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry
  run:
    - python >=3.6,<4.0
    - dask-core >=2021.4.1,<2023
    - matplotlib-base >=3.4.1,<4.0.0
    - numpy >=1.20.2,<2.0.0
    - pillow >=9.0.0,<10.0.0
    - xarray >=0.18,<1
    - stackstac

test:
  imports:
    - geogif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geogif.readthedocs.io/en/latest/index.html
  summary: Render xarray timestacks into GIFs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
